version: '3.7'

services:
  nginx:
    build: ./auction_web_api/nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./auction_web_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  celery:
    container_name: celery
    build:
      context: ./auction_web_api
    command: celery --app=auction_web_api worker -l DEBUG
    image: django_celery_example_celery_worker
    volumes:
      - static:/static
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

volumes:
  static:
