# Generated by Django 5.0.7 on 2024-08-09 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_item_starting_time_item_starting_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autobid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_auto_bid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_bid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('auto_bid_alert_percentage', models.IntegerField(default=90)),
                ('auto_bidding_active', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
