# Generated by Django 5.0.7 on 2024-08-20 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_autobid_created_at_autobid_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('lost', 'Lost'), ('won', 'Won')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='winning_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_item', to='my_app.bid'),
        ),
    ]
