# Generated by Django 5.0 on 2024-08-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
